[advisories]
ignore = [
    "RUSTSEC-2025-0141", # bincode is unmaintained (transitive dependency of syntect)
    "RUSTSEC-2024-0320", # yaml-rust is unmaintained (transitive dependency of syntect)
]
